sonar.projectKey=gopisuvarna_resume_shortlisting
sonar.organization=gopisuvarna

sonar.sources=backend,frontend/src
sonar.tests=backend/shortlist,frontend/tests

sonar.test.inclusions=backend/shortlist/tests.py,backend/**/tests.py,frontend/tests/**/*.spec.ts,frontend/tests/**/*.spec.tsx,frontend/tests/**/*.test.ts,frontend/tests/**/*.test.tsx

sonar.exclusions=backend/**/migrations/**,backend/**/__pycache__/**,backend/staticfiles/**,backend/media/**,backend/test_media/**,backend/.pytest_cache/**,backend/.mypy_cache/**,frontend/.next/**,frontend/coverage/**,frontend/test-results/**,frontend/node_modules/**,node_modules/**

sonar.coverage.exclusions=frontend/**,backend/manage.py,backend/shortlist/tests.py,backend/**/management/commands/**,backend/applications/models.py,backend/applications/serializers.py,backend/applications/views.py,backend/jobs/models.py,backend/jobs/serializers.py,backend/jobs/views.py,backend/shortlist/hybrid_scorer.py,backend/shortlist/views.py,backend/users/models.py,backend/users/serializers.py,backend/users/views.py,backend/core/asgi.py,backend/core/wsgi.py,backend/core/settings.py,backend/core/test_settings.py,backend/core/urls.py,backend/core/middleware.py

sonar.python.coverage.reportPaths=backend/coverage.xml
