# Generated by Django 5.0.6 on 2026-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_hash_snapshot', models.CharField(db_index=True, help_text='Snapshot of applicant aadhaar_hash at submission time.', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWING', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('OFFERED', 'Offer Extended'), ('HIRED', 'Hired'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('current_role', models.CharField(blank=True, max_length=200)),
                ('notice_period_days', models.PositiveSmallIntegerField(default=30)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('skills_mentioned', models.JSONField(default=list)),
                ('hr_notes', models.TextField(blank=True)),
                ('ai_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_matched_skills', models.JSONField(default=list)),
                ('ai_missing_skills', models.JSONField(default=list)),
                ('ai_recommendation', models.CharField(blank=True, max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ['-applied_at'],
            },
        ),
    ]
