# Generated by Django 5.0.6 on 2026-04-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.RemoveField(
            model_name='application',
            name='aadhaar_hash_snapshot',
        ),
    ]
