# Generated by Django 5.0.6 on 2026-04-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_education_score',
            field=models.FloatField(blank=True, help_text='Education dimension score 0-100 (weight 15%)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_experience_score',
            field=models.FloatField(blank=True, help_text='Experience dimension score 0-100 (weight 35%)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_skills_score',
            field=models.FloatField(blank=True, help_text='Skills dimension score 0-100 (weight 50%)', null=True),
        ),
    ]
