# Generated by Django 5.0.6 on 2026-04-20 03:25

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_ai_education_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hr_notes',
        ),
        migrations.AddField(
            model_name='application',
            name='embedding_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='llm_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='llm_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nlp_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.resume_upload_path),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='ai_education_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='ai_experience_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='ai_skills_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
